### PR TITLE
reflect option "debugmode" and "redirect_on_ok" in sample config

### PR DESCRIPTION
**Pull request by dadaxr**
these two options were missing in the config.yml.dist

### CODE REVIEW

**Comment by jadwigo** [comment]
There are more options missing.

The `debugmode` is not in the sample configuration on purpose: you will only find out about it by reading the readme - and I really want people who turn on debugmode toe be aware of the information in the readme because a lot of the support questions are answered there.

The same goes for the `redirect_on_ok` option - you need a published (and existing) page to redirect to for starters which is explained in the readme.

The sample configuration is there mainly to get you started in this case, and not to swarm you in all available options all at once. And some options are just not there because I forgot to include them.

At the moment I don't think the sample configuration should be updated because the whole extension is being rewritten to being an addon for boltforms - and after that the sample configuration needs to be rewritten as well.

**Comment by dadaxr** [comment]
Clear enough :)

**Comment by GwendolenLynch** [comment]
Also the foundation of what will become SimpleForms v2 was merged today and `debugmode` doesn't exist any longer.

But your contribution is nonetheless appreciated :+1:

**Comment by jadwigo** [comment]
oh, and what @GawainLynch said, thanks for your contribution anyway :+1:

**Pull request closed without merging**
